name: mydelivery_admin
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment: { sdk: '>=2.12.0 <3.0.0' }
dependencies:
  flutter: { sdk: flutter }
  cupertino_icons: ^1.0.4

  core:
    path: features/core/

  authentication:
    path: features/authentication

  delivery:
      path: features/delivery
  dashboard:
    path: features/dashboard
  user_profile:
    path: features/user_profile
  vendor:
    path: features/vendor

dev_dependencies:
  flutter_test: { sdk: flutter }
  flutter_lints: ^1.0.4
  flutter_launcher_icons: ^0.9.2

flutter:
  uses-material-design: true

  assets:
      - assets/images/
  fonts:
    - family: ELMessiri
      fonts:
        - asset: assets/fonts/ELMessiri.ttf
flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/logo_with_bg.jpeg"
  adaptive_icon_background: "#03A9F4"
  adaptive_icon_foreground: "assets/images/ic_launcher_foreground.png"
  remove_alpha_ios: true
