name: core
description: A new Flutter project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  dio: ^4.0.4
  provider: ^6.0.2
  flutter_form_builder: ^9.1.0
  form_builder_validators: ^11.0.0
  location: ^7.0.0
  geocoding: ^3.0.0
  cool_alert: ^2.0.1
  intl: ^0.19.0
  shared_preferences: ^2.3.2
  shimmer: ^2.0.0
  cached_network_image: ^3.3.0
  flutter_staggered_animations: ^1.0.0
  pretty_dio_logger: ^1.1.1
  card_swiper: ^2.0.4
  url_launcher: ^6.0.18
  photo_view: ^0.14.0
  form_builder_image_picker: ^4.0.0
  flutter_speed_dial: ^5.0.0+1
  mime: ^1.0.1
  cloud_firestore: ^5.2.1
  animated_text_kit: ^4.2.1
  curved_navigation_bar: ^1.0.3
  flutter_rating_bar: ^4.0.1
  record: ^5.1.2
  audioplayers: ^6.0.0
  flutter_typeahead: ^5.2.0
  flutter_contacts: ^1.1.9+2
  package_info_plus: ^8.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  build_runner: ^2.1.7


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

# To add assets to your package, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
#
# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware.

# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/custom-fonts/#from-packages
